#!/bin/sh
# Pushes a new version to PyPi. Run from root directory.
access_token="$(head -n 1 ../.token.txt)"
lib_dir="pyps4_2ndscreen/__version__.py"
major="$(head -n 3 "$lib_dir" | tail -n 1 | tail -c 2)"
minor="$(head -n 4 "$lib_dir" | tail -n 1 | tail -c 2)"
patch="$(head -n 5 "$lib_dir" | tail -n 1 | tail -c 2)"
VERSION=$(printf "%s.%s.%s" $major $minor $patch)
OWNER="ktnrg45"
REPOSITORY="pyps4-2ndscreen"

git checkout dev
git pull
git merge master
rm -rf dist
python3 setup.py sdist bdist_wheel
python3 -m twine check dist/*
python3 -m twine upload dist/* --skip-existing

git checkout master
read -p "Enter release message: " msg
API_JSON=$(printf '{"tag_name": "%s","target_commitish": "master","name": "%s","body": "%s","draft": false,"prerelease": false}' $VERSION $VERSION $msg)
curl -H "Authorization: token $access_token" --data "$API_JSON" https://api.github.com/repos/:"$OWNER"/:"$REPOSITORY"/releases
